export { default as Main } from './Main/Main'
export { default as BlogPage } from './Blog/BlogPage'
export { default as ProjectPage } from './Project/ProjectPage'
export { default as LoginPage } from './Login/LoginPage'
export { default as GridPage } from './Grid/GridPage'